name: CD - Deploy GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Preparar publicação
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v6

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Preparar arquivos para publicação
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'

  deploy:
    name: Publicar no GitHub Pages
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Publicar site
        id: deployment
        uses: actions/deploy-pages@v4