name: Alerta Discord

on:
  push:
    branches:
      - main

jobs:
  discord:
    name: Enviar alerta para o Discord
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificação
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\":\"🚀 Novo commit realizado na branch main do repositório devflow-pucpr!\"}" \
          "${{ secrets.DISCORD_WEBHOOK }}"