name: Alerta Discord

on:
  push:
    branches:
      - main
      - feature/cicd

jobs:
  discord:
    name: Enviar alerta para o Discord
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificação
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\":\"🚀 Novo commit realizado no repositório devflow-pucpr! Branch: ${{ github.ref_name }}\"}" \
          "${{ secrets.DISCORD_WEBHOOK }}"